version: "3.8"
services:
  sewing_api:
    image: "sewing_api"
    container_name: "sewing_api"
    build: ./api
    ports:
      - "8080:8080"

  sewing_ui:
    image: "sewing_ui"
    container_name: "sewing_ui"
    build: .
    ports:
      - "3000:3000"
