import Head from "next/head";
import Layout from "@/components/layout";
import {
  Chart,
  Series,
  SeriesTemplate,
  CommonSeriesSettings,
  Title,
  Tooltip,
} from "devextreme-react/chart";
import PocketBase from "pocketbase";
import { useEffect, useReducer } from "react";
import styles from "@/styles/Home.module.css";
import OverviewCard from "@/components/home/OverviewCard";
export default function Home() {
  const [thisYearMonthData, dispatchMonths] = useReducer((state, action) => {
    const months = [
      {
        month: "1",
        income: 20000,
      },
      {
        month: "2",
        income: 1000,
      },
      {
        month: "3",
        income: 10000,
      },
      {
        month: "4",
        income: 200000,
      },
      {
        month: "5",
        income: 0,
      },
      {
        month: "6",
        income: 0,
      },
      {
        month: "7",
        income: 0,
      },
      {
        month: "8",
        income: 0,
      },
      {
        month: "9",
        income: 0,
      },
      {
        month: "10",
        income: 0,
      },
      {
        month: "11",
        income: 0,
      },
      {
        month: "12",
        income: 0,
      },
    ];
    action.map((order) => {
      const month = months.find(
        (month) => order.created.slice(6, 7) === month.month
      );
      if (month)
        month.income +=
          parseInt(order.quantity) + parseInt(order.price_per_unit);
    });

    return months;
  }, []);
  const [orderIncomes, disptachOrderIncomes] = useReducer(
    (state, action) => {
      const totalIncome = action.reduce(
        (prevValue, currValue) =>
          parseInt(currValue.quantity) * parseInt(currValue.price_per_unit) +
          prevValue,
        0
      );
      const totalYearIncome = action.reduce((prevValue, currValue) => {
        if (currValue.created.slice(0, 4) == new Date().getFullYear()) {
          return (
            parseInt(currValue.quantity) * parseInt(currValue.price_per_unit) +
            prevValue
          );
        }
        return prevValue;
      }, 0);
      return {
        totalIncome,
        totalYearIncome,
      };
    },
    { totalIncome: 0, totalYearIncome: 0 }
  );
  const [completedOrders, dispatchCompletedOrders] = useReducer(
    (state, action) => {
      return action.reduce(
        (prevValue, currValue) => {
          if (currValue.completed) {
            prevValue[0].counter++;
          } else {
            prevValue[1].counter++;
          }
          return prevValue;
        },
        [
          {
            status: "completed",
            counter: 0,
          },
          {
            status: "uncompleted",
            counter: 0,
          },
        ]
      );
    }
  );
  console.log(completedOrders);
  useEffect(() => {
    (async () => {
      const pb = new PocketBase("http://127.0.0.1:8090");
      const orders = await pb.collection("orders").getFullList({
        batch: "-1",
        filter: `created >= "${new Date().getFullYear()}"`,
      });
      dispatchMonths(orders);
      disptachOrderIncomes(orders);
      dispatchCompletedOrders(orders);
    })();
  }, []);
  return (
    <>
      <Head>
        <title> GUEDIRA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ display: "flex", gap: "1rem" }} className="mt-5">
        <div style={{ width: "50%" }}>
          <div className={styles.cards_container}>
            <OverviewCard
              title={"Total Orders Income"}
              value={orderIncomes.totalIncome}
            />
            <OverviewCard
              title={`Total Orders income in ${new Date().getFullYear()}`}
              value={orderIncomes.totalYearIncome}
            />
          </div>
          <Chart dataSource={thisYearMonthData}>
            <CommonSeriesSettings
              argumentField="month"
              valueField="income"
              type="bar"
              ignoreEmptyPoints={true}
            />
            <SeriesTemplate nameField="month" />
            <Title
              text="Month Orders Breakdown"
              subtitle={`as of ${new Date().getFullYear()}`}
            />
            <Tooltip
              enabled={true}
              format={{
                style: "currency",
                currency: "MAD",
              }}
            />
          </Chart>
        </div>
        <Chart dataSource={completedOrders} width={"45%"}>
          <CommonSeriesSettings
            argumentField="status"
            valueField="counter"
            type="bar"
            ignoreEmptyPoints={true}
          />
          <SeriesTemplate nameField="status" />
          <Title text="Orders Status Breakdown" subtitle={`All Orders`} />
          <Tooltip enabled={true} />
        </Chart>
      </div>
      <Layout page={"Home"}></Layout>
    </>
  );
}
