import Head from "next/head";
import Layout from "@/components/layout";

import OrderCharts from "@/components/home/charts/OrderCharts";
import ClientCharts from "@/components/home/charts/ClientCharts";
export default function Home() {
  console.log(
    "http://" +
      (process.env.NODE_ENV === "production"
        ? "sewing_api:8080"
        : "127.0.0.1:8090") +
      "/api/collections/orders/records?perPage=-1&limit=-1"
  );
  return (
    <>
      <Head>
        <title> GUEDIRA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout page={"Home"}>
        <OrderCharts />
        <hr style={{ height: "1px" }} />
        <ClientCharts />
      </Layout>
    </>
  );
}
